/**
 * Markdown generator for K-12 CS Education scope & sequence plans
 * Follows best practices from CSTA, SF CSforAll, and state standards research
 */

import {
  Plan,
  ScopeSequenceEntry,
  CurriculumRecommendation,
  ImplementationPhase,
  CSTA_CONCEPTS,
  CSTA_PRACTICES,
} from './templates';

/**
 * Generates a comprehensive markdown document from a plan
 */
export function generateMarkdown(plan: Plan): string {
  const sections: string[] = [];

  // Title
  sections.push(`# ${plan.title}`);
  sections.push('');

  // Metadata
  if (plan.createdAt) {
    sections.push(`*Generated: ${new Date(plan.createdAt).toLocaleDateString()}*`);
    sections.push('');
  }

  // Executive Summary
  if (plan.executiveSummary) {
    sections.push('## Executive Summary');
    sections.push('');
    sections.push(plan.executiveSummary);
    sections.push('');
  }

  // Scope & Sequence Table
  if (plan.scopeSequence && plan.scopeSequence.length > 0) {
    sections.push('## Scope & Sequence by Grade Level');
    sections.push('');
    sections.push(generateScopeSequenceTable(plan.scopeSequence));
    sections.push('');
  }

  // Curriculum Recommendations
  if (plan.curriculumRecommendations && plan.curriculumRecommendations.length > 0) {
    sections.push('## Curriculum Recommendations');
    sections.push('');
    sections.push(generateCurriculumSection(plan.curriculumRecommendations));
    sections.push('');
  }

  // Implementation Roadmap
  if (plan.implementationRoadmap && plan.implementationRoadmap.length > 0) {
    sections.push('## Implementation Roadmap');
    sections.push('');
    sections.push(generateImplementationSection(plan.implementationRoadmap));
    sections.push('');
  }

  // Professional Development
  if (plan.professionalDevelopment) {
    sections.push('## Professional Development');
    sections.push('');
    sections.push(generatePDSection(plan.professionalDevelopment));
    sections.push('');
  }

  // Success Metrics
  if (plan.successMetrics) {
    sections.push('## Success Metrics');
    sections.push('');
    sections.push(generateMetricsSection(plan.successMetrics));
    sections.push('');
  }

  // Standards Reference
  sections.push('## Standards Reference');
  sections.push('');
  sections.push(generateStandardsReference());
  sections.push('');

  // Raw Content (if available)
  if (plan.rawContent) {
    sections.push('## Additional Details');
    sections.push('');
    sections.push(plan.rawContent);
    sections.push('');
  }

  // Footer
  sections.push('---');
  sections.push('');
  sections.push('*Generated by [Jamelna K-12 CS Education Planner](https://jamelna.com/k12-cs-education)*');

  return sections.join('\n');
}

/**
 * Generates a markdown table for scope & sequence
 */
function generateScopeSequenceTable(entries: ScopeSequenceEntry[]): string {
  const lines: string[] = [];

  // Header
  lines.push('| Grade Level | Key Competencies | Instruction Time | Recommended Curricula | CSTA Standards |');
  lines.push('|-------------|------------------|------------------|----------------------|----------------|');

  // Rows
  for (const entry of entries) {
    const competencies = entry.competencies?.slice(0, 3).join(', ') || '-';
    const curricula = entry.curricula?.slice(0, 2).join(', ') || '-';
    const standards = entry.standards?.slice(0, 3).join(', ') || '-';

    lines.push(
      `| ${entry.gradeLevel} | ${competencies} | ${entry.instructionTime || '-'} | ${curricula} | ${standards} |`
    );
  }

  return lines.join('\n');
}

/**
 * Generates curriculum recommendations section
 */
function generateCurriculumSection(recommendations: CurriculumRecommendation[]): string {
  const lines: string[] = [];

  for (const rec of recommendations) {
    lines.push(`### ${rec.name}`);
    lines.push('');
    lines.push(`**Provider:** ${rec.provider}`);
    lines.push('');
    lines.push(`**Grade Levels:** ${rec.gradeLevels?.join(', ') || 'All'}`);
    lines.push('');

    if (rec.features && rec.features.length > 0) {
      lines.push('**Key Features:**');
      for (const feature of rec.features) {
        lines.push(`- ${feature}`);
      }
      lines.push('');
    }

    if (rec.rationale) {
      lines.push(`**Why This Curriculum:** ${rec.rationale}`);
      lines.push('');
    }

    if (rec.resources) {
      lines.push(`**Resources:** ${rec.resources}`);
      lines.push('');
    }
  }

  return lines.join('\n');
}

/**
 * Generates implementation roadmap section
 */
function generateImplementationSection(phases: ImplementationPhase[]): string {
  const lines: string[] = [];

  for (const phase of phases) {
    lines.push(`### ${phase.phase}: ${phase.title}`);
    lines.push('');

    if (phase.priorities && phase.priorities.length > 0) {
      lines.push('**Priorities:**');
      for (const priority of phase.priorities) {
        lines.push(`- [ ] ${priority}`);
      }
      lines.push('');
    }
  }

  return lines.join('\n');
}

/**
 * Generates professional development section
 */
function generatePDSection(pd: {
  essential?: string[];
  certifications?: string[];
  support?: string[];
}): string {
  const lines: string[] = [];

  if (pd.essential && pd.essential.length > 0) {
    lines.push('### Essential Training');
    for (const item of pd.essential) {
      lines.push(`- ${item}`);
    }
    lines.push('');
  }

  if (pd.certifications && pd.certifications.length > 0) {
    lines.push('### Certification Pathways');
    for (const item of pd.certifications) {
      lines.push(`- ${item}`);
    }
    lines.push('');
  }

  if (pd.support && pd.support.length > 0) {
    lines.push('### Ongoing Support');
    for (const item of pd.support) {
      lines.push(`- ${item}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Generates success metrics section
 */
function generateMetricsSection(metrics: {
  measurements?: string[];
  milestones?: string[];
}): string {
  const lines: string[] = [];

  if (metrics.measurements && metrics.measurements.length > 0) {
    lines.push('### Key Measurements');
    for (const item of metrics.measurements) {
      lines.push(`- ${item}`);
    }
    lines.push('');
  }

  if (metrics.milestones && metrics.milestones.length > 0) {
    lines.push('### Milestones');
    for (const item of metrics.milestones) {
      lines.push(`- ${item}`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Generates standards reference section with CSTA concepts and practices
 */
function generateStandardsReference(): string {
  const lines: string[] = [];

  lines.push('### CSTA K-12 Core Concepts');
  lines.push('');
  for (const concept of CSTA_CONCEPTS) {
    lines.push(`- ${concept}`);
  }
  lines.push('');

  lines.push('### CSTA K-12 Core Practices');
  lines.push('');
  for (const practice of CSTA_PRACTICES) {
    lines.push(`- ${practice}`);
  }
  lines.push('');

  lines.push('### Grade Band Standard Prefixes');
  lines.push('');
  lines.push('| Grade Band | CSTA Prefix | Example |');
  lines.push('|------------|-------------|---------|');
  lines.push('| K-2 | 1A | 1A-CS-01, 1A-AP-10 |');
  lines.push('| 3-5 | 1B | 1B-CS-02, 1B-AP-08 |');
  lines.push('| 6-8 | 2 | 2-CS-01, 2-AP-13 |');
  lines.push('| 9-12 | 3A/3B | 3A-CS-01, 3B-AP-10 |');

  return lines.join('\n');
}

export default generateMarkdown;
